apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-managed-stage-1
  #namespace: stage
spec:
  template: aws-standalone-cp-1-0-12
  credential: aws-cluster-identity-cred
  config:
    clusterLabels:
      env: stage
    region: eu-central-1
    controlPlane:
      instanceType: t3.medium
    worker:
      instanceType: t3.medium
