apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k0rdent-config
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: management/kcm
    repoURL: https://github.com/wsoualhi/k0rdent-gitops
