apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  name: stage
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: stage
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/wsoualhi/k0rdent-gitops
  roles:
  - description: stage project administrator
    groups:
    - stage
    name: admin
    policies:
    - p, proj:stage:admin, *, *, *, allow
status: {}
