apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusterdeployments-stage
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/wsoualhi/k0rdent-gitops
        revision: HEAD
        directories:
          - path: clusters/stage/*
  template:
    metadata:
      name: 'clusters-{{path.basename}}'
    spec:
      project: stage
      source:
        repoURL: https://github.com/wsoualhi/k0rdent-gitops
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: stage
