apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-secrets
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: stage
  source:
    path: credentials/stage
    repoURL: https://github.com/wsoualhi/k0rdent-gitops
