apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  name: dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: '*'
    name: 'dev-*'
  sourceRepos:
  - https://github.com/wsoualhi/k0rdent-gitops
  roles:
  - description: dev project administrator
    groups:
    - dev
    name: admin
    policies:
    - p, proj:dev:admin, *, *, *, allow
status: {}
